### ISSUE TITLE
ListBoxItem (that opens a dialog) remains grayed 

### ISSUE THREAD

**Issue by ctrl-alt-d** [AvaloniaCommunity/Material.Avalonia#103]
I have a simple ListBox with ListBoxItems.

When I click on a menu on ListBoxItem, the row remains grayed until I click again on it:

![listboxitem](https://user-images.githubusercontent.com/3105983/129556469-3f00d93c-9ef5-45c4-818a-9dffa84e5918.gif)

How can I fix it? Thanks!

**Comment by SKProCH** [comment]
Hello, @ctrl-alt-d 

Seems like this dark background is a selection in `ListBox`.
There is 2 solutions: 
1. Considering that you do not need a selection, it would be more correct to use an `ItemsRepeater` instead of `ListBox`
2. Add following style to your `Styles` of your `ListBox`:
```xaml
<Style Selector="ListBoxItem:selected /template/ Border#selectedBorder">
  <Setter Property="Opacity" Value="0" />
</Style>
```

Does this resolve your problem?

**Comment by ctrl-alt-d** [comment]
Hi Mr @SKProCH ,

thanks a lot about your fast reply and suggestions.

1. I can switch to `ItemControl` ( neither `ItemRepeater` ) because performance degrades rapidly without virtual scrolling.
2. I tried to apply style but nothing happens. I guess is related to click outside of bounds of control, all runs fine if I replace menu with a button.

Thanks again, all comments are welcome!

**Comment by SKProCH** [comment]
@ctrl-alt-d,

As i know `ItemsRepeater` supports (and designed to work with) virtualization. At least i can display ~6000 icons with labels with perfect performance. But in principle there is not much difference, just the problem is that if you do not need to select items, then you do not need a `ListBox`.

If replacing the `ListBox` solves the problem, then I believe the problem is resolved. If not, then I will dig the styles further and try to help.

**Comment by ctrl-alt-d** [comment]
@SKProCH , Thanks again for your support. As a workaround, I replaced the menu by a button and now all runs fine.

Also, I tried to replace `ListBox` by an `ItemsPresenter`. But, [I don't know why, but `ListBox` is faster.](https://github.com/AvaloniaUI/Avalonia/discussions/6427#discussioncomment-1192093)

Thanks again about your comments, I really appreciate! :heart:

**Comment by SKProCH** [comment]
I'll close issue, feel free to reopen it if you have additional questions.
