### ISSUE TITLE
How to add the DatePicker?

### ISSUE THREAD

**Issue by ctrl-alt-d** [AvaloniaCommunity/Material.Avalonia#104]
Hi People,

this is the first time I need a DatePicker on my app. [I try to add it unsuccessfully](https://github.com/AvaloniaUI/Avalonia/discussions/6440). Digging on Demo I see they are not DatePickers, just a custom date picker dialog.

The question is, how can I add a single DatePicker on my app?

Sorry about this noob question :raised_hands: 

Thanks and best regards.

**Comment by CreateLab** [comment]
It's a bug. We try to fix it as fast as we may. But it may take more than a month. If u may send pr with fix, if u may. thx

**Comment by SKProCH** [comment]
Hello, @ctrl-alt-d 

Hmm, seems like @appleneko2001 hasn't finished this yet.
We should fix it, but, most of us don't have time because of work.
As a workaround consider using `TextBlock` for displaying selected date and button that trigger `DatePickerDialog` to select date. 
We apologize for this, I will try to find time to fix it asap.

**Comment by ctrl-alt-d** [comment]
Thanks @CreateLab and @SKProCH about your fast replies.

@CreateLab, I haven't skills to fix it in a short, just dealing with controls itself, MVVM, reactiveUI, etc. I understand what you mean. Unfortunately, I can't collaborate in this way at this time.

Thanks guys, awesome repo!
