### ISSUE TITLE
Add Demo App to the releases

### ISSUE THREAD

**Issue by MarioGK** [AvaloniaCommunity/Material.Avalonia#105]
Could we add an automated build for the demo App and auto include it on the releases here on Github?
I can work on it, i just want to check if you have any specific CI tool in mind, there are a bunch that are free for open source projects, choose one and i will try to make the pipeline for it.

Thanks for the great project i hope i can help out even if it is a little.

**Comment by Sabuto** [comment]
I can have a look at this, it's pretty easy to do but the only way i know of how to do it is following github flow i.e you create a branch for a change fature/add-something bug/fixed-something etc and then the release builder will add each merge to the changelog?

**Comment by SKProCH** [comment]
Hello, @Sabuto 
Now we adhere to a simple policy that in master - releases, in dev - changes that are ready for work but not yet formed into release. In fact, we now have a GitHub Flow, but with the difference that some changes that are not long in development (such as small changes) are implemented directly in dev without creating an additional branch. We also have a master branch that serves to separate scripts that publish releases from scripts that publish nightly builds.

How does this tool work? I just see an option when at least a raw log is formed simply from commit messages. It would be cool if it could be called locally, because usually I specify the changelog in the package for nuget, so I need to know them to edit and put in the proj file.

**Comment by Sabuto** [comment]
I'll take a look around :) just thinking seeing as you build locally? or atleast add the changelog locally is github actions concrete? or would you consider looking at nukebuild?

**Comment by SKProCH** [comment]
> just thinking seeing as you build locally? or atleast add the changelog locally is github actions concrete?

I don't understand the questions a bit
> would you consider looking at nukebuild?

I don't mind using nukebuild, unless it complicates things a lot.

**Comment by Sabuto** [comment]
Sorry I may have worded it very badly, but you answered it in the second part anyway :)

**Comment by SKProCH** [comment]
Sone with latest buildscript changes. Also expect a web version of demo in near future (I hope)
