### ISSUE TITLE
ContextMenu show unexpected background

### ISSUE THREAD

**Issue by furesoft** [AvaloniaCommunity/Material.Avalonia#109]
If I use a ContextMenu in a ListboxItem the ContextMenu is always darkgray. Content not Readable should be white

**Comment by appleneko2001** [comment]
Hello, Can you provide the version of Material.Avalonia Library that you are using now?  Thanks!

**Comment by furesoft** [comment]
2.3.0

**Comment by appleneko2001** [comment]
I found the reason of this bug happens. There was an `<Setter Property="Padding" Value="1"/>` in TreeView.xaml. I replaced this with value 0 and this bug disappears. I think there could be problem with accuracy of layout calculations of avalonia.
Anyway, this issue has fixed with tricky way, and fix has applied to next nightly version. 

Demo:

https://user-images.githubusercontent.com/38249047/132122319-82607516-3212-4e6c-9024-a6dcee6fac1d.mp4

**Comment by appleneko2001** [comment]
I just did an mistake. But dont worry! I'm working for this now.

**Comment by appleneko2001** [comment]
I just pushed an fix to fix this. There was an broken select highlighter behaviour in `MenuItem` and it becomes dark when you adding `MenuItem` in `ListBoxItem`.

Nightly builds with fix:
https://github.com/AvaloniaCommunity/Material.Avalonia/actions/runs/1202885497

**Comment by furesoft** [comment]
when do you publish in to the normal nuget feed?

**Comment by appleneko2001** [comment]
This question should be answered by @SKProCH 
Because I'm not working for shipping releases. But we will shipping packages after some major changes, or a lot minor fixes.

**Comment by SKProCH** [comment]
Hello, @furesoft 

You can [use our nightly builds](https://github.com/AvaloniaCommunity/Material.Avalonia/wiki/Using-nightly-build-feed) feed until we release next release version.

Is this suitable for you?

**Comment by furesoft** [comment]
because my product is close to the first release I don't want to use nightly builds

**Comment by SKProCH** [comment]
New package [v2.3.1](https://www.nuget.org/packages/Material.Avalonia/2.3.1) released.
