### ISSUE TITLE
Unable to integrate version 2.3.1 into existing application

### ISSUE THREAD

**Issue by davidvanelk** [AvaloniaCommunity/Material.Avalonia#112]
When integrating Material.Avalonia@2.3.1 into my App.axaml, a `TargetInvocationException` is thrown when using the Application.Styles-based approach of README.md:

```xaml
<Application.Styles>
        <FluentTheme Mode="Light" />
        <StyleInclude Source="avares://Avalonia.Themes.Default/DefaultTheme.xaml"/>
        <StyleInclude Source="avares://Avalonia.Themes.Default/Accents/BaseLight.xaml"/>
        <StyleInclude Source="avares://Material.Avalonia/Material.Avalonia.Templates.xaml" />
    </Application.Styles>
```

Runtime exception thrown on Startup:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingFieldException: Field not found: 'Avalonia.Controls.FlyoutPresenter.CornerRadiusProperty'.
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/FlyoutPresenter.axaml(IServiceProvider , Styles )
   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/FlyoutPresenter.axaml(IServiceProvider )
   at CompiledAvaloniaXaml.!XamlLoader.TryLoad(String )
   --- End of inner exception stack trace ---
```

After Downgrading to Material.Avalonia@2.3.0 everything works as expected. 

Following some relevant NuGet-Packages that are included into my project:

```csproj
<PackageReference Include="Avalonia" Version="0.10.7" />
<PackageReference Include="Avalonia.Desktop" Version="0.10.7" />
<PackageReference Include="Avalonia.Diagnostics" Version="0.10.7" />
<PackageReference Include="Avalonia.ReactiveUI" Version="0.10.7" />
<PackageReference Include="Material.Avalonia" Version="2.3.0" />
```

**Comment by appleneko2001** [comment]
Hello! This problem is related with FlyoutPresenter's CornerRadius setter. To make it works, we have to update AvaloniaUI package to latest (0.10.7) version for our package (sounds weird right?).
So I updated Material.Avalonia library to this version, and everything starts working again.
For now, I submitted an fixes for this on `dev-branch` and the fix is available on nightly builds!

PS: why we always pushing updates without any corrections lmao (FACEPALM)
