### ISSUE TITLE
How to apply a new theme using the MaterialThemeBase

### ISSUE THREAD

**Issue by teocomi** [AvaloniaCommunity/Material.Avalonia#170]
Hey there, I'm updating my code from using the old `PaletteHelper` to the new `MaterialTheme` but cannot find a way to update the current theme. 
I simply want to toggle between dark/light, everything worked as expected previously...

My App.xaml:
```xml
  <Application.Styles>
    <themes:MaterialThemeBase />
    <StyleInclude Source="avares://Material.Avalonia/Material.Avalonia.Templates.xaml" />
    <StyleInclude Source="avares://Material.Icons.Avalonia/App.xaml" />
    <StyleInclude Source="/Styles/Styles.xaml" />
  </Application.Styles>
```

My OnFrameworkInitializationCompleted:
```csharp
  var theme = Theme.Create(Theme.Light, Primary, Accent);
  var themeBootstrap = this.LocateMaterialTheme<MaterialThemeBase>();
   themeBootstrap.CurrentTheme = theme;
```

My toggle theme code:
```csharp
var materialTheme = Application.Current.LocateMaterialTheme<MaterialThemeBase>();
materialTheme.CurrentTheme.SetBaseTheme(Theme.Dark);
```

**Comment by SKProCH** [comment]
Hello, @teocomi   
Sorry for the long wait for an answer

`materialTheme.CurrentTheme` is a property that generates a new theme object for you each time, so that users cannot change the internal theme from the outside (since changing the theme will not change the styles). So when you do `materialTheme.CurrentTheme.SetBaseTheme(Theme.Dark);` you change an object that has nothing to do with what's inside `MaterialThemeBase`. You need to change the properties you want in the theme object and then assign it back, you do that:

```cs
var materialTheme = Application.Current.LocateMaterialTheme<MaterialThemeBase>();
var theme = materialTheme.CurrentTheme.SetBaseTheme(Theme.Dark);
materialTheme.CurrentTheme = theme;
```

Does this solve your problem?

**Comment by teocomi** [comment]
Hey @SKProCH thanks for your support! I just tried unfortunately this doesn't seem to work either.
I can put together a quick sample app if that helps...

And thanks for the great library!

**Comment by SKProCH** [comment]
@teocomi  
Yes, I think it would make it easier to find the problem if you gave me an sample app. Or you can just share link to the actual one.

**Comment by SKProCH** [comment]
Hello, @teocomi 

I took a look at your project. Apparently this problem was fixed in the nightly builds. At least with `3.0.0-rc0.90-nightly` everything works. 

I hope that soon I will have enough time to post a stable rc, in the meantime, use the nightly build.

**Comment by teocomi** [comment]
It does indeed work! Sorry for opening a non-issue & thanks for checking 💥
