### ISSUE TITLE
Tooltip not working when used on Slider control

### ISSUE THREAD

**Issue by flarive** [AvaloniaCommunity/Material.Avalonia#174]
Hi,

My project is using latest version of Material Avalonia (2.5.1) and latest version of Avalonia (0.10.15)
If add a tooltip on a Slider control themed by Material Avalonia, the tooltip is showing but without any text inside.

To reproduce the issue, you can for exemple, in SliderDemo.xaml, add a tooltip tip on the first slider :
<Slider ToolTip.Tip="aaaaaaaaaa" />

The result is shown by the screen capture (the gray rectangle is the empty tooltip) :
![bug_slider_tooltip_empty](https://user-images.githubusercontent.com/7724904/176407042-414eaa02-beba-4d13-9fee-166f15d2a5d5.png)

In debug mode i have this binding error in VS output :
[Binding] Error in binding to 'Avalonia.Controls.TextBlock'.'Text': 'Could not find a matching property accessor for 'Children' on 'Avalonia.Controls.ToolTip'' (TextBlock #11127745)

Thanks for your help :)

Eviral

**Comment by SKProCH** [comment]
Hello, @flarive 

This problem is caused by the fact that we had special styles for the demo app and the slider page. These styles allowed you to associate a slider value with a text block to display that value.

In idea this error can't be reproduced in normal applications. If it does reproduce - check your styles that modify TextBlock.

The error is fixed in the demo.

**Comment by flarive** [comment]
Works perfectly !
Thanks a lot !!!
