### ISSUE TITLE
ProgressBar ShowProgressText has no effect

### ISSUE THREAD

**Issue by EricZeiberg** [AvaloniaCommunity/Material.Avalonia#184]
Not sure if this is a bug or the feature is simply not implemented yet, but setting the property `ShowProgressText="true"` has no effect on the ProgressBar.

**Comment by SKProCH** [comment]
Hello, @EricZeiberg 

Yep, seems like this is an some kind of new Avalonia feature.  
For now, I don't know how to implement this within the Material.Design concept, but I'll think about it. If you have any ideas, I'd love to read them.

**Comment by EricZeiberg** [comment]
You could do something like Bootstrap does where the text is inside of the bar: https://getbootstrap.com/docs/4.0/components/progress/#labels

**Comment by SKProCH** [comment]
The problem is [Material Design guidelines](https://material.io/components/progress-indicators#usage) tells up, what we should do progressbar small in terms of height.  
![image](https://user-images.githubusercontent.com/29896317/196271557-35e57890-fc7b-4d31-a1c4-134c17984d6c.png)
I think what we can add text inside circular ProgressBar, and make taller version of regular.

**Comment by SKProCH** [comment]
Hello, @EricZeiberg 

I've implemented this in new nightly version. You can try in now
