### ISSUE TITLE
Avalonia 11.0.0-preview5 compatibility

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaCommunity/Material.Avalonia#217]
Currently there is nightly release `3.0.0-avalonia11-preview3.145-nightly` with preview-5 support published.  
This is just combability fixes and changes to allow compiling and running apps with preview-5. 
I'm sure that because of the changes in avalonia, something might not work. 

**If you encounter any errors**, create an issue or post in the comments to that.
-------
Current TODO list:
- [x] Crashes when clicking on virtualizable list elements in Demo project. This is issue on the Avalonia side: https://github.com/AvaloniaUI/Avalonia/issues/10374 
- [x] Support for Avalonia [RequestedTheme feature](https://github.com/AvaloniaUI/Avalonia/pull/8166)
- [x] Fix Slider styles
- [x] Fix TabControl styles

**Comment by SKProCH** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/10374 is actually fixed right now, you should use the nightly Avalonia release. But perhaps you should recompile Material.Avalonia yourself for nightly Avalonia version (or not). I don't want to release package what depends on nightly builds.

**Comment by marklam** [comment]
There are a couple of new properties on ListBox - `AreHorizontalSnapPointsRegular` and `AreVerticalSnapPointsRegular` that are passed down to the ItemsPresenter and StackPanel/VirtualizingStackPanel in the built-in themes, but they're not in the Material theme.

https://github.com/search?q=repo%3AAvaloniaUI%2FAvalonia+areverticalsnappointsregular+language%3AXML&type=code&l=XML

Without them, a list with huge number of entries slows to a crawl when scrolling, because every entry is inspected to decide its size.

**Comment by SKProCH** [comment]
Yep, added this now. Thanks, @marklam

**Comment by SKProCH** [comment]
Closed as fixed in https://github.com/AvaloniaCommunity/Material.Avalonia/releases/tag/3.0.0-avalonia11-preview4
