### ISSUE TITLE
SelectableTextBlock cannot select any font

### ISSUE THREAD

**Issue by qfmee** [AvaloniaCommunity/Material.Avalonia#243]
In Material.Avalonia  **SelectableTextBlock** cannot select any font!  But Avalonia can!

**Comment by qfmee** [comment]
It was good before the RC1 version！

**Comment by SKProCH** [comment]
Hello, what did you mean by "select any font"? Set custom font?

**Comment by qfmee** [comment]
![无标题](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/74282924/0076ca56-fc0f-47e3-b8e8-ca23c76b2f85)
No，Like this, select the text！This img is avalonia RC1，No problem ！but In Material.Avalonia not work

**Comment by qfmee** [comment]
![无标题](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/74282924/0076ca56-fc0f-47e3-b8e8-ca23c76b2f85)
No，Like this, select the text！This img is avalonia RC1，No problem ！but In Material.Avalonia not work

**Comment by SKProCH** [comment]
This fixed in last nightly version. You can [install and use](https://github.com/AvaloniaCommunity/Material.Avalonia/wiki/Using-nightly-build-feed) latest nightly version [nuget](https://github.com/AvaloniaCommunity/Material.Avalonia/packages/572265) or wait until stable version of package has been released on Nuget feed.
