### ISSUE TITLE
Add styles for `TitleBar` to support close/maximize buttons when ExtendClientAreaToDecorationsHint=True

### ISSUE THREAD

**Issue by lxymahatma** [AvaloniaCommunity/Material.Avalonia#246]
Avalonia Version: 11.0.0-rc1.1
Material.Avalonia Package Version: 3.0.0-avalonia11-preview4.179-nightly

Project window when using Simple Style:
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/66151783/3f06c7e4-45e4-44e5-a5fe-55ca06bcf45d)

Project window when using Material Theme with style: <themes:MaterialTheme BaseTheme="Dark" PrimaryColor="Grey" SecondaryColor="Indigo" />
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/66151783/e9d6675f-0c37-4bdd-a5af-cf3aa9e31517)

**Comment by SKProCH** [comment]
Hello, @lxymahatma 

Seems like this will caused by the fact what we missing styles for `TitleBar`. I'll try to implement it, but i can't guarantee what it will be fast. For now you can use FluentTheme for this.
Your `App.axaml` should be look like this:
```xaml
<Application.Styles>
  <FluentTheme/>
  <themes:MaterialTheme PrimaryColor="Purple" SecondaryColor="Indigo" />
  ...
```
So, it will use most of the styles from MaterialTheme, but missing styles should be pulled from FluentTheme and TitleBar should be shown.
