### ISSUE TITLE
DialogHost not working anymore

### ISSUE THREAD

**Issue by Mrxx99** [AvaloniaCommunity/Material.Avalonia#283]
Starting with version 3.0.0-avalonia11-preview6.12-nightly the DialoHost is shown empty:
![grafik](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/33566379/cc15cde7-c540-4a2c-ace0-24f270602d64)
Works fine with version 3.0.0-avalonia11-preview6.10-nightly and below.
Using DialogHost.Avalonia 0.7.6

You can test it here: https://github.com/Mrxx99/YoutubeDownloader/tree/dialoghost-issue (defined in RootView.xaml)
Just launch the app and you will see above screenshot, downgrading one version will work fine
(or use https://github.com/Mrxx99/YoutubeDownloader/tree/feature/avalonia-port) for comparison.

Since it started failing with 3.0.0-avalonia11-preview6.12-nightly I suspect this is the commit responsible:
https://github.com/AvaloniaCommunity/Material.Avalonia/commit/6452073eaadc2b01f9352b2a03f69e988a275438
Which is about SnackbarHost and I have placed a SnackBarHost inside the DialogHost, but it still happens if I remove it.

**Comment by SKProCH** [comment]
Hello, @Mrxx99 

This is caused by user custom style for UserControls. This is defined in App.axaml:
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/29896317/7c3b0aba-2a66-4925-a810-4af0f7ce14cb)

And referenced here: 
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/29896317/7355c197-603f-4857-a496-84c56984d133)

In Material I'll migrate everything to ControlThemes to avoid "styles leaking". So, UserControl migrated too - https://github.com/AvaloniaCommunity/Material.Avalonia/commit/408a5628ba8879839083d65816c1ecf4ecc361da

This is the reason why you don't see anything - your UserControls missing Template. You can remove styles, or add BasedOn to your control theme: `BasedOn="{StaticResource MaterialUserControl}". 

Hope this helps.

**Comment by Mrxx99** [comment]
Thank you very much, that works! Thought it must be an issue in Material.Avalonia because it worked in older version, but I understand the reason now
