### ISSUE TITLE
Rider's Avalonia preview will not work when using Material.Avalonia using version 3.2.X

### ISSUE THREAD

**Issue by imJack6** [AvaloniaCommunity/Material.Avalonia#343]
### Usage Information

Material.Avalonia=3.2.2 / Avalonia=11.0.7 / Windows 11 / AvaloniaRider=1.3.0 / Rider=2023.3 Nightly

### Description

While using Material.Avalonia version 3.2.2, I encountered an issue related to Rider's Avalonia preview functionality. The specific manifestation is that after applying Material.Avalonia 3.2.X version in the project, Rider's Avalonia interface design preview function cannot work properly.

### Reproduction Steps

Use Rider to create an Avalonia project, add and apply the Material.Avalonia theme with version 3.2.X, and the AvaloniaRider plug-in will be invalid.

### Expected Behavior

1. Using Rider
2. Using Material.Avalonia 3.2.2
3. Apply styles in App.axaml
4. The preview of MainWindow will get stuck, which should be an error.

### Actual Behavior

Rider's Avalonia preview function fails when using Material.Avalonia 3.2.2 version. When I rolled back to Material.Avalonia 3.1.3 version, the preview functionality returned to normal.

### Regression?

This issue seems to have occurred after upgrading from Material.Avalonia 3.1.3 to version 3.2.X. In version 3.1.3, Rider's Avalonia preview function can be used normally.

### Anything else?

https://github.com/AvaloniaCommunity/Material.Avalonia/assets/58357771/8846c28d-df67-4535-90f5-3df233754542

### Could you help with a pull-request?

No

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by SKProCH** [comment]
I'll try to address this in the near future.

**Comment by SKProCH** [comment]
Long story short:

Max Katz, [Thu, 01/25/2024 1:55]
@SKProCH in general the problem is that Material no longer explicitly references the Avalonia.Markup assembly for one reason or another (which is normal in general).

Max Katz, [Thu, 01/25/2024 1:55]
But the runtime compiler tries to reflectively extract types from this assembly, which is not loaded in a clean application

Max Katz, [Thu, 01/25/2024 1:56]
The runtime compiler of the previewer should preload all these assemblies, but in 11.0 there is a bug that not all assemblies are preloaded, but only the first of each nuget of the package (skipping Avalonia.Markup).

We should wait for fix backporting and probably use the nightly Avalonia version till new release is out. I'll test it tomorrow.

**Comment by SKProCH** [comment]
Seems like `11.0.999-cibuild0043921-beta` fixes the problem.

If not - clear nuget cache: 
```shell
dotnet nuget locals all --clear
```
