### ISSUE TITLE
Set FloatingButton as style

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaCommunity/Material.Avalonia#63]
`<Button Style="Floating"/>`

**Comment by appleneko2001** [comment]
Make floating button as style of button is meanless. Since it behaviors not like button. For example, FAB can switch state (Default or Extended).

Actually, we can implement this technically if you really want, but I dont recommend do this. Maybe we should make an public polls first to know this is important or not?

**Comment by SKProCH** [comment]
Closing since floating buttons are implemented via [FloatingButton control](https://github.com/AvaloniaCommunity/Material.Avalonia/blob/dev/Material.Styles/FloatingButton.xaml)
